import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import CompaniesView from "@/pages/companiesView";
import {ApolloClient, InMemoryCache, ApolloProvider} from "@apollo/client";
import CompaniesViewUsingQuery from "@/pages/companiesViewUsingHooks";
import CompaniesViewUsingLazyHooks from "@/pages/companiesViewUsingLazyHooks";

const inter = Inter({subsets: ['latin']})
const apolloClient = new ApolloClient({
    uri: "http://localhost:8080/graphql",
    cache: new InMemoryCache()    //cache: new InMemoryCache({resultCaching: false}),
});


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <ApolloProvider client={apolloClient}>
                    <CompaniesViewUsingLazyHooks/>
                </ApolloProvider>
            </main>
        </>
    )
}
