version: '3.7'
services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
        - 6379:6379
        volumes:
        - ./data:/data
        command: redis-server --appendonly yes
    redis-gui:
        image: redislabs/redisinsight:1.14.0
        container_name: redis-gui
        ports:
         - 8002:8001
