services:
  palindrome-api:
    image: palindrome-api:1.0.0
    container_name: palindrome-api
    build:
      context: ./palindrome-api
    ports:
      - "8082:8080"

  word-api:
    image: word-api:1.0.0
    container_name: word-api
    build:
      context: ./word-api
    ports:
      - "8081:8080"
    depends_on: palindrome-api
