quarkus:
  datasource:
    db-kind: mysql
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    jdbc:
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3006}/training
  hibernate-orm:
    log:
      sql: true
  application:
    name: quarkus-lab04
    version: 1.0.0
  package:
    type: uber-jar
  smallrye-openapi:
    enable: true
    info-title: Quarkus Lab04
    info-version: 1.0.0
    info-description: Last day of week
