apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-api-config
  namespace: mexico
data:
  WELCOME: "Hello from Kubernetes config map in  aks!"
  BYE: "Goodbye from Kubernetes config map in aks!"
  DATABASE_URL: "jdbc:mysql://host.docker.internal:3306/training"
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-api-secret
  namespace: mexico
data:
  DATABASE_USERNAME: cm9vdAo= # echo "root" | base64
  DATABASE_PASSWORD: dHJhaW5pbmcK # echo "training" | base64
