services:
  quarkus-lab04-api:
    image: quarkuslab04:1.0.0
    container_name: quarkus-lab04
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=host.docker.internal